import { createClient } from '@/lib/supabase/server'
import { Card, CardContent, CardHeader } from '@/ui/card'
import { Button } from '@/ui/rac/button'
import { Form } from '@/ui/rac/form'
import { Separator } from '@/ui/rac/separator'
import { TextField } from '@/ui/rac/text-field'
import { UserRoundIcon } from 'lucide-react'
import dynamic from 'next/dynamic'
import { notFound } from 'next/navigation'
import React from 'react'
import { TextArea } from 'react-aria-components'
const Player = dynamic(() => import('@/ui/player').then(mod => mod.Player), {
  ssr: false,
})

export default async function Module({
  params,
}: { params: { id: string; module: string } }) {
  const supabase = createClient()
  const { data, error } = await supabase
    .from('modules')
    .select('*')
    .eq('id', params.module)
    .limit(1)
    .single()

  if (error) {
    throw error
  }

  if (!data) {
    notFound()
  }

  return (
    <div className="flex gap-4">
      <div className="flex flex-col flex-grow gap-y-2">
        <div className="flex flex-col max-w-screen-lg">
          <div className="aspect-video">
            <Player
              src={data.video}
              thumbnail={data.thumbnail}
              thumbnails=""
              title={data.title}
            />
          </div>
          <div className="pt-2 pb-8">
            <h2 className="text-2xl text-balance font-bold">{data.title}</h2>
            <p className="text-gray-500 text-pretty">{data.description}</p>
          </div>
        </div>
        <div>
          <h3 className="text-xl font-semibold">Comments</h3>
        </div>
        <div className="flex flex-col border p-4 gap-y-2 rounded-lg my-4">
          <div className="bg-gray-100 p-4 rounded-lg">
            <Form
              action={async () => {
                'use server'
              }}
            >
              <div>
                <div className="flex gap-x-2 items-center">
                  <UserRoundIcon />
                  <strong>John Doe</strong>
                </div>
                <div className="pl-8 my-4">
                  <TextField label="Comment" />
                </div>
              </div>
            </Form>
          </div>
          {[
            { user: { name: 'John Doe', id: 1 }, content: 'Awesome!!' },
            {
              user: { name: 'Jane Doe', id: 2 },
              content: 'I love this video!',
            },
            {
              user: { name: 'John Doe', id: 3 },
              content: 'This is great!',
            },
          ].map(comment => (
            <React.Fragment key={comment.user.id}>
              <Separator />
              <div className="flex gap-x-2 pt-4 items-center">
                <UserRoundIcon />
                <strong>{comment.user.name}</strong>
              </div>
              <div className="pl-8 py-4">
                <p className="text-gray-500">{comment.content}</p>
              </div>
            </React.Fragment>
          ))}
        </div>
      </div>
      <div className="flex flex-col gap-y-4 basis-1/2 flex-shrink">
        <Card className="max-w-screen-md">
          <CardHeader>
            <h3 className="mb-2 text-lg font-bold">
              Add a summary of the video (Autogenerated AI Feature coming soon!)
            </h3>
            <Form
              action={async () => {
                'use server'
              }}
            >
              <TextArea
                className="w-full border-2 border-gray-200 bg-white rounded-md p-2 outline-none border-spacing-2"
                placeholder="Write a summary of the video"
              />
              <button className="bg-blue-500 text-white rounded-md p-2 mt-2">
                Submit
              </button>
            </Form>
          </CardHeader>
          <CardContent>
            <p>
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Adipisci
              labore consequuntur totam ducimus cupiditate iure dolor, vel
              reprehenderit quis praesentium voluptates autem numquam eos
              debitis doloribus dolores facilis commodi dignissimos deleniti
              magnam voluptatem nemo tempore voluptatum. Nihil, quasi rem. Unde
              tenetur doloremque maxime sequi recusandae velit sed quam rem!
              Eveniet.
            </p>
          </CardContent>
        </Card>
        <Card className="max-w-screen-md">
          <CardHeader>
            <h3 className="my-2 text-lg font-bold">
              Add a quiz question for your students to answer
            </h3>
            <Form>
              <TextField label="Question" name="question" />
              <TextField label="Answer" name="answer" />
              <Button type="submit">Add Question</Button>
            </Form>
          </CardHeader>
          <Separator />
          <CardContent>
            <Form
              className="my-8"
              action={async () => {
                'use server'
              }}
            >
              <TextField label="Question 1" />
              <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit.
                Excepturi porro molestias explicabo consequuntur? Alias vitae
                nesciunt in? Autem tenetur unde dolorem dolorum, soluta suscipit
                libero sunt est beatae a quas corporis assumenda explicabo modi
                nemo pariatur? Nam iste eos sunt! Illo perferendis facilis,
                assumenda numquam ullam fuga quia eligendi voluptates.
              </p>
              <Button type="submit">Answer Question</Button>
            </Form>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}
